### ISSUE TITLE
Update infra README with some additional details

### ISSUE THREAD

**Issue by AlexanderTitus** [In-Vivo-Group/NHANES-GPT#9]
- Enable Identity and Access Management (IAM) API in project

**Comment by AlexanderTitus** [comment]
Also update the information to tell the user to run these commands in the cloud shell, give a screen shot of what the end output should look like, and not that once the shell command is complete, to check Compute Engine to verify an instance is running and note it will take ~7hours and then will shut itself down. 

<img width="1587" alt="Screenshot 2024-01-05 at 07 44 52" src="https://github.com/In-Vivo-Group/NHANES-GPT/assets/15268064/c42a84d5-d61d-4a0d-a2b9-3aae597e876f">

<img width="1040" alt="Screenshot 2024-01-05 at 07 49 21" src="https://github.com/In-Vivo-Group/NHANES-GPT/assets/15268064/75495663-48d4-4a98-9996-448e7291905b">

**Comment by brk21** [comment]
I believe the updated README satisfies these requirements. The permissions issue is just an issue of timing. We will cause the deployment to sleep for a couple minutes to try to minimize those errors.
